import React, { useState } from 'react';
import { CalendarDays, BriefcaseBusiness, FileText, Bell, LogOut, ArrowRight, MessageCircle, X, Minus, Paperclip, Send, Clock3, ClipboardCheck, Users, ChevronRight, Check, Star, MapPin, Sparkles, CircleHelp, Sun, Leaf, CalendarPlus, Activity, AlertCircle } from 'lucide-react';
import './client-home.css';

type Props={navigate:(id:'team'|'hours'|'calendar'|'records'|'documents'|'reports')=>void};
const tasks=[['ENTREGÁVEL 1','Em andamento','03 de out','warm'],['Revisão de políticas','Não iniciado','05 de out','red'],['Alinhamento de gestores','Em andamento','15 de out','purple'],['Leitura executiva','Em andamento','23 de out','green']];
const kinds=['Dúvida','Mudança de contexto','Solicitação','Ocorrência'];
const quick=[['Próxima reunião','calendar'],['Horas do ciclo','hours'],['Validações','validation'],['Relatórios','reports']];
const people=[['MC','Mariana','Ativa','green'],['PR','Pedro','Ativo','green'],['CF','Camila','Em férias','yellow'],['RG','Rafael','Ativo','green']];
export default function ClientHome({navigate}:Props){
 const [chat,setChat]=useState(false),[min,setMin]=useState(false),[kind,setKind]=useState('Dúvida'),[message,setMessage]=useState(''),[toast,setToast]=useState(''),[menu,setMenu]=useState<'frentes'|'alerts'|null>(null),[detail,setDetail]=useState<string|null>(null);
 const say=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),4200)};
 return <div className="client-home">
 <div className="ch-toolbar"><div className="ch-area"><span className="ch-area-mark"/><span><small>ÁREA DA EMPRESA</small><strong>Início</strong></span></div><div className="ch-tools">
 <button aria-label="Abrir agenda" className="ch-tool gold" onClick={()=>navigate('calendar')}><CalendarPlus size={17}/></button>
 <button className="ch-tool pill" onClick={()=>setMenu(menu==='frentes'?null:'frentes')}><BriefcaseBusiness size={17}/> Frentes</button>
 <button aria-label="Documentos" className="ch-tool" onClick={()=>navigate('documents')}><FileText size={17}/><span className="ch-badge">1</span></button>
 <button aria-label="Tema claro" className="ch-tool" onClick={()=>say('A V2 está sendo construída exclusivamente no tema claro.')}><Sun size={17}/></button>
 <button aria-label="Notificações" className="ch-tool" onClick={()=>setMenu(menu==='alerts'?null:'alerts')}><Bell size={17}/><span className="ch-badge">1</span></button>
 <button aria-label="Sair" className="ch-tool" onClick={()=>say('Esta é uma demonstração; não há sessão de cliente para encerrar.')}><LogOut size={17}/></button>
 </div></div>
 {menu&&<div className="ch-menu"><button onClick={()=>setMenu(null)} aria-label="Fechar"><X size={14}/></button><strong>{menu==='frentes'?'Frentes contratadas':'Notificações'}</strong><p>{menu==='frentes'?'Estrutura e governança · Desenvolvimento de liderança · Processos de pessoas':'Uma validação fictícia aguarda seu retorno. O ambiente ainda não está conectado aos dados reais.'}</p></div>}
 <div className="ch-content">
 <div className="ch-greeting"><div><span className="ch-overline">SUA PARCERIA COM A CALI</span><h1>Olá, Paula.</h1><p>Veja o que aconteceu e o que vem a seguir na sua assessoria.</p></div><div className="ch-executive"><span className="ch-executive-photo">PL</span><div><small>RESPONSÁVEL EXECUTIVA DA CONTA</small><strong>Patrícia Lima</strong><span>People Advisory Executive</span></div></div></div>
 <section className="ch-contract"><div className="ch-contract-top"><div className="ch-contract-name"><div className="ch-company-logo">A<span>·</span></div><div><small>SUA CONTRATAÇÃO</small><h2>CALI Partner</h2><span>Aurora Tecnologia</span></div></div><div className="ch-contract-figures"><div><strong>0h</strong><span>consumidas no mês · 0%</span></div><div><strong>15h</strong><span>contratadas no mês</span></div></div></div><div className="ch-contract-progress"><div className="ch-progress-line"><span/></div><div><span>0h</span><span>50%</span><span>15h</span></div></div></section>
 <div className="ch-three"><section className="ch-surface ch-deliveries"><h3>Entregas do ciclo</h3><div className="ch-delivery-inside"><div><strong className="ch-big">4</strong><p>entregas no projeto atual</p></div><div className="ch-donut"><span>0%</span></div><div className="ch-legend"><span><i className="green"/> Aprovadas <b>0</b></span><span><i className="yellow"/> Pendentes <b>4</b></span><span><i className="red"/> Canceladas <b>0</b></span></div></div></section>
 <section className="ch-surface ch-feeling"><h3>Percepção do trabalho <span>· mês atual</span></h3><div className="ch-feeling-inner"><div><p><Star size={17} color="#bb5372"/> <strong>0 avaliações recebidas</strong></p><p><Check size={17} color="#1b927f"/> Aguardando a primeira</p></div><div className="ch-no-rating"><strong>—</strong><small>Sem nota</small></div></div><small className="ch-subnote">De entregas ou ocorrências</small></section>
 <section className="ch-surface ch-completion"><h3>Conclusão do trabalho <span>· mês atual</span></h3><div className="ch-complete-line"><strong className="ch-big">0%</strong><div className="ch-color-bars"><i/><i/><i/><i/><i/></div></div><p>0 de 0 atividades concluídas entre entregas e ocorrências.</p></section></div>
 <div className="ch-mid"><section className="ch-surface ch-recent-document"><div className="ch-doc-thumb"><FileText size={31}/><span>CALI</span></div><div><small className="ch-kicker">DOCUMENTO MAIS RECENTE</small><h3>Entregável 1</h3><p>Atualizado em 29 de setembro de 2026</p><button className="ch-link" onClick={()=>navigate('documents')}>Ver documento e acervo <ChevronRight size={14}/></button></div></section>
 <section className="ch-surface ch-recent-case"><div className="ch-avatars"><span>MC</span><span>PL</span><span>AR</span></div><span className="ch-tag amber">Aguardando você</span><small className="ch-kicker">OCORRÊNCIA MAIS RECENTE</small><h3>Promoção interna</h3><p>Registrada há 28 dias · 1 em aberto</p><button className="ch-link" onClick={()=>navigate('records')}>Abrir ocorrência <ChevronRight size={14}/></button></section>
 <section className="ch-surface ch-people"><div className="ch-card-head"><h3>Minha equipe hoje</h3><button className="ch-link" onClick={()=>navigate('team')}>Ver equipe <ArrowRight size={13}/></button></div><div className="ch-people-count"><strong>4</strong> colaboradores</div><div className="ch-avatars large">{people.map(([initial,name,status,color])=><button title={name+' · '+status} key={name} className={color} onClick={()=>setDetail(name)}>{initial}</button>)}</div><div className="ch-person-status"><span><i className="green"/>3 ativos</span><span><i className="yellow"/>1 em férias</span><span><i className="red"/>0 afastados</span></div></section></div>
 <div className="ch-bottom"><section className="ch-surface ch-project"><div className="ch-card-head"><div><small className="ch-kicker">EM MOVIMENTO</small><h3>Estrutura e governança</h3></div><button className="ch-link" onClick={()=>say('A página do projeto será integrada após a aprovação do layout.')} >Ver projeto <ArrowRight size={14}/></button></div><div className="ch-gantt"><div className="ch-gantt-header"><span>ENTREGA / STATUS</span><span>INÍCIO</span><span>MEIO</span><span>CONCLUSÃO</span></div>{tasks.map(([name,status,date,color],i)=><button key={name} className="ch-gantt-row" onClick={()=>setDetail(name)}><div><strong>{name}</strong><small>{status}</small></div><div className="ch-gantt-track"><span className={'ch-milestone '+color} style={{left:(9+i*22)+'%'}}>{date}</span></div></button>)}<div className="ch-gantt-foot"><span>01 out</span><span>13 out</span><span>25 out</span></div></div></section>
 <section className="ch-side-stack"><section className="ch-surface ch-next"><div className="ch-card-head"><div><small className="ch-kicker">PRÓXIMOS PASSOS</small><h3>Agenda compartilhada</h3></div><button className="ch-link" onClick={()=>navigate('calendar')}>Abrir <ArrowRight size={13}/></button></div><div className="ch-event"><div className="ch-event-date"><strong>20</strong><small>OUT</small></div><span className="ch-event-dot"/><div><strong>Visita presencial extra</strong><small>12:00 · Presencial</small><span><MapPin size={12}/> Escritório da empresa</span></div></div></section><section className="ch-surface ch-cycle-next"><div className="ch-card-head"><h3>Próxima decisão</h3><span className="ch-tag lilac">Em validação</span></div><p>Revisão de responsabilidades de liderança</p><button className="ch-link" onClick={()=>setDetail('Revisão de responsabilidades')}>Consultar contexto <ArrowRight size={13}/></button></section></section></div>
 </div>
 <button className="ch-chat-trigger" onClick={()=>{setChat(true);setMin(false)}}><span className="ch-chat-portrait">P</span> Fale com a Pati <MessageCircle size={15}/></button>
 {chat&&<div className={'ch-chat '+(min?'minimized':'')}><div className="ch-chat-top"><span className="ch-chat-portrait">P</span><div><small>CANAL DIRETO CALI</small><strong>Fale com a Pati</strong><span>People Advisory Executive</span></div><button title="Minimizar" onClick={()=>setMin(!min)}><Minus size={15}/></button><button title="Fechar" onClick={()=>setChat(false)}><X size={16}/></button></div>{!min&&<div className="ch-chat-body"><p>Consulte informações da sua conta ou registre algo que precise de acompanhamento da CALI.</p><div className="ch-chat-quick"><small>POSSO RESPONDER AGORA</small><div>{quick.map(([label,id])=><button key={id} onClick={()=>{if(id==='hours')navigate('hours');else if(id==='reports')navigate('reports');else if(id==='calendar')navigate('calendar');else say('A validação será conectada ao fluxo oficial.')}}>{id==='calendar'?<CalendarDays size={13}/>:id==='hours'?<Clock3 size={13}/>:id==='validation'?<ClipboardCheck size={13}/>:<Activity size={13}/>} {label}</button>)}</div></div><div className="ch-chat-kinds">{kinds.map(x=><button key={x} className={x===kind?'selected':''} onClick={()=>setKind(x)}>{x}</button>)}</div><label htmlFor="ch-message">Sua mensagem</label><textarea id="ch-message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Escreva aqui. Isso ficará registrado na sua conta CALI."/ ><div className="ch-chat-send"><button title="Anexos indisponíveis nesta demo" onClick={()=>say('Anexos indisponíveis na versão demonstrativa.')}><Paperclip size={15}/></button><button onClick={()=>say('Demonstração visual: nenhuma mensagem foi enviada.')} disabled={!message.trim()}><Send size={13}/> Enviar para a Pati</button></div><div className="ch-chat-note"><CircleHelp size={13}/> Respostas e mensagens reais dependem da integração com o canal oficial.</div></div>}</div>}
 {detail&&<div className="ch-overlay" onClick={()=>setDetail(null)}><aside onClick={e=>e.stopPropagation()} className="ch-detail"><button aria-label="Fechar" onClick={()=>setDetail(null)}><X size={19}/></button><small>VISUALIZAÇÃO DEMONSTRATIVA</small><h2>{detail}</h2><p>Esta lateral mostra como detalhes podem ser abertos sem perder o contexto do início. As informações são fictícias e não alteram a produção.</p><span className="ch-tag lilac">Somente demonstração</span></aside></div>}
 {toast&&<div role="status" className="ch-toast"><AlertCircle size={16}/>{toast}</div>}
 </div>
}