import React,{useState} from 'react';
import {Megaphone,Plus,CalendarDays,Check,MessageCircle,Image as ImageIcon,X,Send,Info,ArrowRight,MapPin,Clock3} from 'lucide-react';
import './notices.css';
export type Notice={id:string;title:string;category:string;date:string;time?:string;coverage?:string;description:string;author:string;calendar:boolean;image?:string};
export const noticeSamples:Notice[]=[
{id:'AV-101',title:'Feriado nacional · Nossa Senhora Aparecida',category:'Feriado',date:'2026-10-12',coverage:'Nacional',description:'Em 12 de outubro não haverá atendimento regular da CALI. Demandas em andamento serão retomadas no próximo dia útil; entregas críticas serão combinadas antecipadamente.',author:'CALI · Assessoria',calendar:true,image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80'},
{id:'AV-102',title:'Atendimento em horário reduzido',category:'Atendimento',date:'2026-10-16',time:'09:00 às 13:00',coverage:'Equipe CALI',description:'Na sexta-feira, o atendimento da CALI acontecerá até 13h. Solicitações recebidas depois desse período serão acompanhadas no próximo expediente.',author:'CALI · Assessoria',calendar:true,image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80'},
{id:'AV-103',title:'Próxima leitura executiva do ciclo',category:'Comunicado',date:'2026-10-22',description:'O fechamento do mês consolidará atividades executadas, decisões e próximos passos da parceria.',author:'CALI · Assessoria',calendar:false,image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80'}
];
const fmt=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
export function NoticesView({focusId,onCloseFocus}:{focusId?:string|null;onCloseFocus?:()=>void}){
const [items,setItems]=useState<Notice[]>(noticeSamples),[active,setActive]=useState<string|null>(null),[filter,setFilter]=useState('Todos'),[ack,setAck]=useState<string[]>([]),[comments,setComments]=useState<Record<string,string[]>>({}),[comment,setComment]=useState(''),[composing,setComposing]=useState(false),[draft,setDraft]=useState({title:'',category:'Feriado',date:'2026-10-19',time:'',coverage:'Nacional',description:'',calendar:true,image:''});
const selected=items.find(x=>x.id===(focusId||active));const categories=['Todos','Feriado','Atendimento','Comunicado'];
const toggleAck=(id:string)=>setAck(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);
return <div className="notice-page">
<div className="notice-title"><div><small>ÁREA DA EMPRESA / COMUNICAÇÃO</small><h1>Quadro de Avisos<span>.</span></h1><p>Comunicados da parceria, datas importantes e informações de atendimento.</p></div><button className="notice-main-button" onClick={()=>setComposing(true)}><Plus size={16}/> Novo comunicado</button></div>
<div className="notice-demo"><Info size={14}/> Demonstração visual com dados fictícios. Publicação e sincronização real dependem da integração.</div>
<div className="notice-toolbar"><div className="notice-filters">{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><span>{items.filter(x=>filter==='Todos'||x.category===filter).length} publicações</span></div>
<div className="notice-list">{items.filter(x=>filter==='Todos'||x.category===filter).map(n=><article key={n.id} className={'notice-item '+n.category.toLowerCase()}>{n.image&&<div className="notice-cover"><img src={n.image} alt={n.title}/><span className={'notice-cover-tag '+n.category.toLowerCase()}>{n.category}</span></div>}<div className="notice-item-main"><div className="notice-item-top"><span className="notice-author-mark">C</span><span><strong>{n.author}</strong><small>{fmt(n.date)} · {n.id}</small></span><span className={'notice-category '+n.category.toLowerCase()}>{n.category}</span></div><h2>{n.title}</h2><p>{n.description}</p>{n.calendar&&<div className="notice-calendar-link"><CalendarDays size={14}/><strong>{fmt(n.date)}</strong>{n.time&&<span>· {n.time}</span>}<span>· Informação vinculada ao calendário</span></div>}<div className="notice-actions"><button className={ack.includes(n.id)?'acknowledged':''} onClick={()=>toggleAck(n.id)}><Check size={15}/>{ack.includes(n.id)?'Ciente registrado':'Estou ciente'}</button><button onClick={()=>{setActive(n.id);setComment('')}}><MessageCircle size={15}/> Comentar {comments[n.id]?.length?'('+comments[n.id].length+')':''}</button></div></div></article>)}</div>
{selected&&<div className="notice-overlay" onMouseDown={()=>{setActive(null);onCloseFocus?.()}}><section className="notice-dialog" role="dialog" aria-modal="true" aria-label="Comunicado" onMouseDown={e=>e.stopPropagation()}><header><span>COMUNICADO · {selected.id}</span><button onClick={()=>{setActive(null);onCloseFocus?.()}} aria-label="Fechar"><X size={19}/></button></header><div className="notice-dialog-body">{selected.image&&<img className="notice-detail-cover" src={selected.image} alt={selected.title}/>}<span className={'notice-category '+selected.category.toLowerCase()}>{selected.category}</span><h2>{selected.title}</h2><p>{selected.description}</p><dl><div><dt>Data</dt><dd>{fmt(selected.date)}</dd></div>{selected.time&&<div><dt>Horário</dt><dd>{selected.time}</dd></div>}{selected.coverage&&<div><dt>Abrangência</dt><dd>{selected.coverage}</dd></div>}<div><dt>Publicado por</dt><dd>{selected.author}</dd></div></dl><h3>Comentários</h3>{!(comments[selected.id]?.length)&&<p className="notice-muted">Nenhum comentário nesta prévia.</p>}{comments[selected.id]?.map((c,i)=><div className="notice-comment" key={i}><strong>Cliente · Aurora</strong><p>{c}</p><small>Prévia local · não enviada</small></div>)}</div><footer><button onClick={()=>toggleAck(selected.id)} className="notice-ack"><Check size={15}/>{ack.includes(selected.id)?'Ciente registrado':'Estou ciente'}</button><div className="notice-write"><input placeholder="Escrever comentário…" value={comment} onChange={e=>setComment(e.target.value)}/><button disabled={!comment.trim()} aria-label="Adicionar comentário de demonstração" onClick={()=>{setComments(v=>({...v,[selected.id]:[...(v[selected.id]||[]),comment]}));setComment('')}}><Send size={17}/></button></div></footer></section></div>}
{composing&&<div className="notice-overlay" onMouseDown={()=>setComposing(false)}><section className="notice-dialog notice-create" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><span>NOVO COMUNICADO · PRÉVIA</span><button onClick={()=>setComposing(false)} aria-label="Fechar"><X size={19}/></button></header><div className="notice-dialog-body"><h2>Publicar no quadro de avisos</h2><p>Uma informação de calendário não vira compromisso: continua vinculada à publicação original.</p><label>Categoria<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value,calendar:e.target.value!=='Comunicado'})}><option>Feriado</option><option>Atendimento</option><option>Comunicado</option></select></label><label>Título<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Ex.: Feriado municipal"/></label><div className="notice-fields"><label>Data<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Horário (opcional)<input value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})} placeholder="09:00 às 13:00"/></label></div><label>Abrangência<select value={draft.coverage} onChange={e=>setDraft({...draft,coverage:e.target.value})}><option>Nacional</option><option>Estadual</option><option>Municipal</option><option>Equipe CALI</option><option>Cliente</option></select></label><label>Imagem de capa (opcional)<input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)setDraft(v=>({...v,image:URL.createObjectURL(file)}))}}/></label>{draft.image&&<img className="notice-compose-cover" src={draft.image} alt="Prévia da capa"/>}<label>Mensagem<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="O que o cliente precisa saber?"/></label><label className="notice-check"><input type="checkbox" checked={draft.calendar} onChange={e=>setDraft({...draft,calendar:e.target.checked})}/> Exibir como informação no calendário (sem bloquear horários)</label><div className="notice-help"><ImageIcon size={15}/> Imagem de capa opcional e permissões por conta serão configuradas na integração.</div></div><footer><button onClick={()=>setComposing(false)}>Cancelar</button><button className="notice-main-button" disabled={!draft.title.trim()||!draft.description.trim()||!draft.date} onClick={()=>{setItems(v=>[{...draft,id:'AV-DEMO-'+(v.length+1),author:'CALI · Prévia local'},...v]);setFilter('Todos');setComposing(false);setDraft({...draft,title:'',description:''})}}>Criar prévia local <ArrowRight size={15}/></button></footer></section></div>}</div>
}