import React,{useState} from 'react';
import {X,Plus,Play,ChevronRight} from 'lucide-react';
import './project-admin-dialogs.css';
type Props={name:string;onClose:()=>void;accountNames:string[]};
const known=['Novo projeto','Nova frente','Novo entregável','Nova tarefa','Editar planejamento'];
export default function ProjectAdminDialogs({name,onClose,accountNames}:Props){
 const [tab,setTab]=useState('Visão geral');
 const [fronts,setFronts]=useState(1);
 const [draft,setDraft]=useState<Record<string,string>>({});
 const set=(k:string,v:string)=>setDraft(p=>({...p,[k]:v}));
 const fresh=known.includes(name);
 const heading=name==='Novo projeto'?'Estruturar cronograma e frentes':name==='Nova frente'?'Adicionar frente ao cronograma':name==='Novo entregável'?'Criar entregável':name==='Nova tarefa'?'Adicionar subtarefa':name==='Editar planejamento'?'Planejamento do projeto':name;
 const field=(label:string,type='text',placeholder='')=><label className="ap-pd-field" key={label}><span>{label}</span><input type={type} value={draft[label]||''} placeholder={placeholder} onChange={e=>set(label,e.target.value)}/></label>;
 const choice=(label:string,choices:string[])=><label className="ap-pd-field" key={label}><span>{label}</span><select value={draft[label]||''} onChange={e=>set(label,e.target.value)}><option value="">Selecionar</option>{choices.map(x=><option key={x}>{x}</option>)}</select></label>;
 return <div className="ap-pd-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="ap-pd-modal" role="dialog" aria-modal="true" aria-label={heading}><header className="ap-pd-head"><div><small>{fresh?'OPERAÇÃO / PROJETOS':'ENTREGÁVEL / GESTÃO'}</small><h2>{heading}</h2><p>{fresh?'Prévia navegável dos campos do fluxo oficial. Nenhuma alteração será gravada.':'Visão administrativa do entregável, suas etapas, conversa e histórico.'}</p></div><button className="ap-pd-close" aria-label="Fechar" onClick={onClose}><X size={19}/></button></header>
 {!fresh&&<nav className="ap-pd-tabs">{['Visão geral','Subtarefas','Conversa','Histórico'].map(x=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</nav>}
 <div className="ap-pd-body">
 {name==='Novo projeto'&&<><div className="ap-pd-fields">{choice('Cliente',accountNames)}{field('Nome do projeto','text','Roadmap People · ciclo estratégico')}{field('Início','date')}{field('Meta desejada (opcional)','date')}</div><div className="ap-pd-subhead"><h3>Frentes iniciais</h3><button onClick={()=>setFronts(x=>x+1)}><Plus size={14}/> Frente</button></div>{Array.from({length:fronts},(_,i)=><div className="ap-pd-front" key={i}><span>{String(i+1).padStart(2,'0')}</span>{choice('Frente '+(i+1),['Pessoas & Performance','Estrutura e Governança','Cultura','Liderança','Outro'])}{field('Objetivo da frente '+(i+1))}{fronts>1&&<button onClick={()=>setFronts(x=>Math.max(1,x-1))}>Remover</button>}</div>)}<p className="ap-pd-note">A janela M1–M8 é calculada a partir dos entregáveis vinculados, como no fluxo oficial.</p></>}
 {name==='Nova frente'&&<><div className="ap-pd-fields">{choice('Nome da frente',['Pessoas & Performance','Estrutura e Governança','Cultura','Liderança','Outro'])}<label className="ap-pd-field"><span>Objetivo / contexto</span><textarea value={draft.Objetivo||''} onChange={e=>set('Objetivo',e.target.value)}/></label></div><p className="ap-pd-note">Frentes já usadas na mesma conta não devem ser duplicadas. O período será calculado pelos entregáveis.</p></>}
 {name==='Novo entregável'&&<div className="ap-pd-fields">{field('Título')}{choice('Frente',['Pessoas & Performance','Estrutura e Governança','Cultura','Liderança'])}{choice('Complexidade',['MC1','MC2','MC3'])}{field('Prazo','date')}{choice('Mês inicial',['M1','M2','M3','M4','M5','M6','M7','M8'])}{choice('Mês final',['M1','M2','M3','M4','M5','M6','M7','M8'])}<label className="ap-pd-field ap-pd-wide"><span>Descrição</span><textarea value={draft.Descrição||''} onChange={e=>set('Descrição',e.target.value)}/></label><label className="ap-pd-check"><input type="checkbox" defaultChecked/> Visível para o cliente</label><label className="ap-pd-check"><input type="checkbox"/> Entrega documental</label></div>}
 {name==='Nova tarefa'&&<div className="ap-pd-fields">{field('Título da subtarefa')}{field('Prazo','date')}{field('Estimativa de horas','number')}<label className="ap-pd-field ap-pd-wide"><span>Descrição</span><textarea/></label><label className="ap-pd-check"><input type="checkbox"/> Visível ao cliente</label></div>}
 {name==='Editar planejamento'&&<div className="ap-pd-fields">{field('Início','date')}{field('Meta desejada','date')}</div>}
 {!fresh&&tab==='Visão geral'&&<><div className="ap-pd-statgrid"><div><small>Situação</small><b>Em andamento</b></div><div><small>Prazo</small><b>03 out 2026</b></div><div><small>Complexidade</small><b>MC2</b></div><div><small>Frente</small><b>Pessoas & Performance</b></div></div><h3>Sobre esta entrega</h3><p>Prévia de acompanhamento e publicação dos arquivos vinculados ao entregável.</p><button className="ap-pd-inline">Arquivo da entrega <ChevronRight size={14}/></button></>}
 {!fresh&&tab==='Subtarefas'&&<><div className="ap-pd-subhead"><h3>Subtarefas e etapas</h3><button onClick={()=>set('Adicionando subtarefa','sim')}><Plus size={14}/> Subtarefa</button></div>{draft['Adicionando subtarefa']? <div className="ap-pd-fields">{field('Título da subtarefa')}{field('Estimativa de horas','number')}{field('Prazo','date')}{choice('Visibilidade',['Interna','Compartilhada com o cliente'])}</div>:<p className="ap-pd-note">Nenhuma subtarefa cadastrada nesta demonstração.</p>}</>}
 {!fresh&&tab==='Conversa'&&<><div className="ap-pd-chat"><div>Cliente · Solicito revisão do conteúdo apresentado.</div><div>CALI · Vamos consolidar uma nova versão para validação.</div></div><textarea placeholder="Escreva uma mensagem demonstrativa (não será enviada)"/></>}
 {!fresh&&tab==='Histórico'&&<div className="ap-pd-history"><p>29 set · Publicação da versão 1.0</p><p>30 set · Aguardando validação</p><p>01 out · Acompanhamento da CALI</p></div>}
 </div><footer className="ap-pd-footer"><span>HOMOLOGAÇÃO V2 · SEM ALTERAR PRODUÇÃO</span><div>{!fresh&&<button className="ap-pd-inline" onClick={()=>setTab('Subtarefas')}><Play size={13}/> Subtarefas / timer</button>}<button onClick={onClose}>Cancelar</button><button className="ap-pd-primary" onClick={onClose}>{fresh?'Concluir simulação':'Fechar'} <ChevronRight size={14}/></button></div></footer></section></div>
}