import React,{useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Plus,Search,Filter,Clock3,Users,Check,MessageCircle,FileText,X,Send,Paperclip,AlertCircle,ArrowRight,Info,Download,SlidersHorizontal,ChevronDown} from 'lucide-react';
import './workflows.css';
type Nav=(p:'calendar'|'records'|'documents'|'reports'|'hours')=>void;
const days=['Seg 05','Ter 06','Qua 07','Qui 08','Sex 09'];
const events=[
{date:0,kind:'Reunião',title:'Alinhamento com a liderança',at:'09:00',shade:'purple',who:'CALI + Diretoria'},
{date:1,kind:'Atividade',title:'Revisão de indicadores',at:'11:00',shade:'blue',who:'Equipe CALI'},
{date:2,kind:'Entrega',title:'Política de feedback',at:'14:00',shade:'green',who:'CALI'},
{date:3,kind:'Reunião',title:'Check-in de assessoria',at:'10:00',shade:'purple',who:'CALI + Cliente'},
{date:3,kind:'Validação',title:'Cronograma do ciclo',at:'15:00',shade:'yellow',who:'Aguardando cliente'},
{date:4,kind:'Marco',title:'Fechamento de prioridades',at:'16:00',shade:'red',who:'CALI'},
];
const cases=[
{id:'OC-024',title:'Promoção interna',kind:'Movimentação de pessoas',status:'Aguardando cliente',tone:'yellow',updated:'07 out 2026',owner:'CALI + Aurora',detail:'Revisar critérios para formalizar a movimentação e esclarecer os impactos na estrutura.'},
{id:'OC-023',title:'Alinhamento de papéis da liderança',kind:'Governança',status:'Em acompanhamento',tone:'purple',updated:'05 out 2026',owner:'CALI',detail:'Consolidar responsabilidades e discutir próximos passos com a direção.'},
{id:'OC-022',title:'Orientação sobre feedback',kind:'Orientação consultiva',status:'Concluída',tone:'green',updated:'01 out 2026',owner:'CALI',detail:'Orientação registrada e encaminhamentos concluídos.'},
{id:'OC-021',title:'Revisão de integração de equipe',kind:'Processos de pessoas',status:'Em acompanhamento',tone:'blue',updated:'28 set 2026',owner:'Cliente',detail:'Organizar informações para revisão de etapas do processo.'},
];
const docs=[{title:'Entregável 1 · Matriz de responsabilidades',kind:'Entregável',date:'29 set 2026',state:'Disponível',tone:'green'}, {title:'Resumo executivo · Setembro',kind:'Leitura executiva',date:'01 out 2026',state:'Publicado',tone:'purple'}, {title:'Diretrizes de feedback',kind:'Documento de trabalho',date:'27 set 2026',state:'Aguardando ciência',tone:'yellow'}];
function Tag({tone,children}:{tone:string,children:React.ReactNode}){return <span className={'wf-tag '+tone}>{children}</span>}
function DemoBar(){return <div className="wf-demo"><Info size={13}/> Prova de interface · Dados fictícios, sem conexão ao Supabase ou envio de mensagens</div>}
export function CalendarView({navigate}:{navigate:Nav}){
 const [view,setView]=useState<'week'|'month'>('week'),[filter,setFilter]=useState('Todas'),[selected,setSelected]=useState<typeof events[number]|null>(null);
 const [period,setPeriod]=useState(0);const kinds=['Todas','Reunião','Entrega','Validação','Atividade','Marco'];
 const filtered=events.filter(e=>filter==='Todas'||e.kind===filter);
 return <div className="wf"><div className="wf-head"><div><small>ÁREA DA EMPRESA / ACOMPANHAMENTO</small><h1>Agenda compartilhada</h1><p>Reuniões, validações e marcos da assessoria em uma visão única.</p></div><button className="wf-primary" onClick={()=>setSelected({date:3,kind:'Solicitação',title:'Solicitar agendamento',at:'A definir',shade:'purple',who:'Cliente + CALI'})}><Plus size={15}/> Solicitar agendamento</button></div><DemoBar/><div className="wf-controls"><div className="wf-segments"><button className={view==='week'?'on':''} onClick={()=>setView('week')}>Semana</button><button className={view==='month'?'on':''} onClick={()=>setView('month')}>Mês</button></div><button className="wf-inline" onClick={()=>setPeriod(period-1)}><ChevronLeft size={15}/></button><strong>{period===0?'05 a 09 de outubro de 2026':period>0?'Próxima semana':'Semana anterior'}</strong><button className="wf-inline" onClick={()=>setPeriod(period+1)}><ChevronRight size={15}/></button><button className="wf-inline" onClick={()=>setPeriod(0)}>Hoje</button><div className="wf-control-right"><SlidersHorizontal size={15}/><select value={filter} onChange={e=>setFilter(e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select></div></div>
 <div className="wf-calendar"><div className="wf-cal-label"><strong>{view==='week'?'SEMANA DE ACOMPANHAMENTO':'MARCO DO MÊS'}</strong><span>Outubro · CALI Partner</span><div className="wf-cal-legend">{[['purple','Reunião'],['green','Entrega'],['yellow','Validação'],['blue','Análise']].map(([tone,label])=><span key={tone}><i className={tone}/>{label}</span>)}</div></div><div className="wf-calendar-grid">{days.map((d,i)=><div className="wf-cal-day" key={d}><div className={'wf-day-head '+(i===3?'today':'')}><strong>{d}</strong>{i===3&&<span>HOJE</span>}</div><div className="wf-event-list">{period===0?filtered.filter(x=>x.date===i).map((e,j)=><button key={j} className={'wf-event '+e.shade} onClick={()=>setSelected(e)}><time>{e.at}</time><strong>{e.title}</strong><small>{e.who}</small></button>):<div className="wf-no-event">Nenhum dado demonstrativo para este período</div>}</div></div>)}</div></div>
 <div className="wf-footnote">No cliente, este calendário mostra compromissos e entregas da CALI, não jornadas de ponto, férias ou escala de colaboradores.</div>
 {selected&&<div className="wf-overlay" onMouseDown={()=>setSelected(null)}><section className="wf-modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Detalhes da agenda"><div className="wf-modal-header"><span>AGENDA · CALI WORKSPACE</span><button aria-label="Fechar" onClick={()=>setSelected(null)}><X size={18}/></button></div><h2>{selected.title}</h2><Tag tone={selected.shade}>{selected.kind}</Tag><div className="wf-modal-grid"><span>Horário <strong>{selected.at}</strong></span><span>Participantes <strong>{selected.who}</strong></span><span>Período <strong>Outubro de 2026</strong></span></div><p>Detalhe demonstrativo: o evento definitivo poderá exibir instruções, local, participantes e uma trilha de solicitações.</p><div className="wf-modal-actions"><button onClick={()=>setSelected(null)}>Fechar</button><button onClick={()=>{setSelected(null);navigate('records')}} className="wf-primary">Abrir acompanhamento <ArrowRight size={14}/></button></div></section></div>}</div>
}
export function RecordsView(){
 const [q,setQ]=useState(''),[tab,setTab]=useState('Todas'),[open,setOpen]=useState<typeof cases[number]|null>(null),[create,setCreate]=useState(false),[draft,setDraft]=useState({type:'Orientação consultiva',title:'',description:''}),[reply,setReply]=useState(''),[demoMessage,setDemoMessage]=useState(''),[toast,setToast]=useState('');
 const items=cases.filter(c=>(tab==='Todas'||c.status===tab)&&[c.title,c.id,c.kind].join(' ').toLowerCase().includes(q.toLowerCase()));
 const notice=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),3500)};
 return <div className="wf"><div className="wf-head"><div><small>ÁREA DA EMPRESA / CANAL COM A CALI</small><h1>Ocorrências</h1><p>Uma conversa por assunto, com decisões e histórico no mesmo lugar.</p></div><button className="wf-primary" onClick={()=>setCreate(true)}><Plus size={15}/> Nova ocorrência</button></div><DemoBar/>
 <div className="wf-summary-inline"><span><strong>4</strong> registros</span><span><i className="wf-dot yellow"/>1 aguardando cliente</span><span><i className="wf-dot purple"/>2 em acompanhamento</span><span><i className="wf-dot green"/>1 concluído</span></div>
 <div className="wf-controls"><div className="wf-segments"><button onClick={()=>setTab('Todas')} className={tab==='Todas'?'on':''}>Todas</button><button onClick={()=>setTab('Aguardando cliente')} className={tab==='Aguardando cliente'?'on':''}>Aguardando você</button><button onClick={()=>setTab('Em acompanhamento')} className={tab==='Em acompanhamento'?'on':''}>Em acompanhamento</button><button onClick={()=>setTab('Concluída')} className={tab==='Concluída'?'on':''}>Concluídas</button></div><div className="wf-control-right"><Search size={14}/><input aria-label="Buscar ocorrências" placeholder="Buscar ocorrência..." value={q} onChange={e=>setQ(e.target.value)}/></div></div>
 <div className="wf-records"><div className="wf-record-row header"><span>Protocolo / Assunto</span><span>Tipo</span><span>Última atualização</span><span>Situação</span><span/></div>{items.map(c=><button className="wf-record-row" key={c.id} onClick={()=>{setOpen(c);setReply('')}}><span><small>{c.id}</small><strong>{c.title}</strong></span><span>{c.kind}</span><span>{c.updated}</span><span><Tag tone={c.tone}>{c.status}</Tag></span><ChevronRight size={16}/></button>)}{!items.length&&<div className="wf-empty">Não há ocorrências nesse filtro.</div>}</div>
 <div className="wf-footnote">Histórico e ações são somente de demonstração nesta etapa. A V2 real preservará protocolo, anexos, notificações e autoria.</div>
 {open&&<div className="wf-overlay" onMouseDown={()=>setOpen(null)}><aside className="wf-record-drawer" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Detalhes da ocorrência"><header><div><small>OCORRÊNCIA · {open.id}</small><h2>{open.title}</h2></div><button onClick={()=>setOpen(null)} aria-label="Fechar"><X size={18}/></button></header><div className="wf-drawer-meta"><Tag tone={open.tone}>{open.status}</Tag><span>{open.kind}</span><span>Atualizado {open.updated}</span></div><div className="wf-story"><small>REGISTRO INICIAL</small><p>{open.detail}</p></div><div className="wf-thread"><h3>Conversa e encaminhamentos</h3><div className="wf-bubble received"><strong>CALI · Assessoria</strong><p>Registramos o contexto da solicitação para acompanhamento. Vamos consolidar as orientações e os próximos passos.</p><small>07 out · 09:45</small></div><div className="wf-bubble sent"><strong>Cliente · Aurora</strong><p>Obrigada! Podemos alinhar a proposta antes do próximo encontro?</p><small>07 out · 10:15</small></div>{demoMessage&&<div className="wf-bubble sent"><strong>Mensagem de teste (não enviada)</strong><p>{demoMessage}</p><small>Prévia local</small></div>}</div><div className="wf-compose"><label htmlFor="wf-answer">Responder nesta ocorrência</label><textarea id="wf-answer" placeholder="Escreva sua mensagem para a CALI…" value={reply} onChange={e=>setReply(e.target.value)}/><div><button className="wf-inline" onClick={()=>notice('Anexos estarão disponíveis após integração de segurança.')}><Paperclip size={14}/> Anexar</button><button className="wf-primary" disabled={!reply.trim()} onClick={()=>{setDemoMessage(reply);setReply('');notice('Prévia local criada — nada foi enviado.')}}><Send size={14}/> Demonstrar envio</button></div></div></aside></div>}
 {create&&<div className="wf-overlay" onMouseDown={()=>setCreate(false)}><section className="wf-modal wf-create" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Nova ocorrência"><div className="wf-modal-header"><span>NOVA OCORRÊNCIA · DEMONSTRAÇÃO</span><button onClick={()=>setCreate(false)} aria-label="Fechar"><X size={18}/></button></div><h2>O que você precisa acompanhar?</h2><p>Registre o contexto de forma objetiva. A equipe CALI avaliará e conduzirá os próximos passos conforme o serviço contratado.</p><div className="wf-form"><label>Tipo de ocorrência<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option>Orientação consultiva</option><option>Movimentação de pessoas</option><option>Mudança de contexto</option><option>Solicitação de apoio</option></select></label><label>Assunto<input placeholder="Ex.: Revisão de responsabilidades" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Descreva a situação<textarea placeholder="Qual é o contexto, o que mudou e qual apoio você precisa?" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="wf-info"><Info size={15}/> Nenhum registro será criado no Supabase. Este formulário serve apenas para validar o fluxo e a estética.</div></div><div className="wf-modal-actions"><button onClick={()=>setCreate(false)}>Cancelar</button><button className="wf-primary" disabled={!draft.title.trim()||!draft.description.trim()} onClick={()=>{notice('Fluxo demonstrado. Nenhuma ocorrência foi gravada.');setCreate(false);setDraft({type:'Orientação consultiva',title:'',description:''})}}>Visualizar confirmação <ArrowRight size={14}/></button></div></section></div>}
 {toast&&<div className="wf-toast"><Info size={14}/>{toast}</div>}
 </div>
}
export function DocumentsView({navigate}:{navigate:Nav}){const [selected,setSelected]=useState<typeof docs[number]|null>(null);return <div className="wf"><div className="wf-head"><div><small>ÁREA DA EMPRESA / ACERVO</small><h1>Documentos</h1><p>Documentos publicados, versões e ciência em uma lista objetiva.</p></div><button onClick={()=>navigate('records')} className="wf-outline">Solicitar documento <ArrowRight size={14}/></button></div><DemoBar/><div className="wf-records"><div className="wf-record-row header"><span>Documento</span><span>Categoria</span><span>Atualização</span><span>Estado</span><span/></div>{docs.map(d=><button key={d.title} className="wf-record-row" onClick={()=>setSelected(d)}><span><strong><FileText size={15}/> {d.title}</strong></span><span>{d.kind}</span><span>{d.date}</span><span><Tag tone={d.tone}>{d.state}</Tag></span><ChevronRight size={16}/></button>)}</div><div className="wf-footnote">A versão final manterá o comportamento validado de documentos: permissões, versões, anexos e registros de ciência.</div>{selected&&<div className="wf-overlay" onMouseDown={()=>setSelected(null)}><section className="wf-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="wf-modal-header"><span>DOCUMENTO · PRÉVIA</span><button onClick={()=>setSelected(null)}><X size={17}/></button></div><h2>{selected.title}</h2><p>Visualização demonstrativa. O documento real, suas versões e ações de ciência serão ligados ao serviço de documentos depois dos testes.</p><Tag tone={selected.tone}>{selected.state}</Tag><div className="wf-modal-actions"><button onClick={()=>setSelected(null)}>Fechar</button></div></section></div>}</div>}
export function ReportsView(){const [period,setPeriod]=useState('Setembro de 2026');return <div className="wf"><div className="wf-head"><div><small>ÁREA DA EMPRESA / LEITURA EXECUTIVA</small><h1>Relatórios</h1><p>Fatos, evolução e encaminhamentos — não apenas gráficos.</p></div><button className="wf-outline" onClick={()=>{}}><Download size={14}/> PDF após integração</button></div><DemoBar/><div className="wf-controls"><strong>Fechamento do ciclo</strong><div className="wf-control-right"><CalendarDays size={14}/><select value={period} onChange={e=>setPeriod(e.target.value)}><option>Setembro de 2026</option><option>Agosto de 2026</option></select></div></div><div className="wf-report-layout"><section className="wf-report-paper"><span>LEITURA EXECUTIVA · DEMONSTRAÇÃO</span><h2>O que avançou em {period.toLowerCase()}</h2><p>Uma narrativa objetiva que conecta entregas, fatos observados, decisões e próximos passos da parceria.</p><div className="wf-report-section"><h3>01 · Contexto do período</h3><p>Estrutura de liderança e processos de gestão de pessoas seguem como prioridades do ciclo.</p></div><div className="wf-report-section"><h3>02 · Evidências e entregas</h3><div className="wf-report-line"><strong>Estrutura e governança</strong><Tag tone="green">Em execução</Tag></div><div className="wf-report-line"><strong>Diretrizes de feedback</strong><Tag tone="yellow">Em validação</Tag></div></div><div className="wf-report-section"><h3>03 · Decisões necessárias</h3><p>Validar o escopo das responsabilidades e confirmar a próxima reunião executiva.</p></div></section><aside className="wf-report-side"><h3>Sobre a leitura</h3><p>Na versão oficial, cada informação deverá ter fonte, período e status de publicação.</p><ul><li>Produzido pela CALI</li><li>Publicado ao cliente</li><li>Histórico de versões</li><li>Registro de ciência</li></ul></aside></div></div>}
